### ISSUE TITLE
Landing Page

### ISSUE THREAD

**Issue by KingLyrics** [InternPulse/team-tesla-frontend#2]
Landing page is yet to be built.

**Comment by KingLyrics** [comment]
Landing page is looking good. Though you can create a mockdata for the testimonials and map over it with a component so that at least when we get the api I it would be okay.

**Comment by KingLyrics** [comment]
David, the designers will get back to you on the design to pick for the Landing page. So corrections will still have to be made for the landing page.

**Comment by AgonoDavid** [comment]
It seems they have concluded on the final design, because i  am seeing an update on figma
