### ISSUE TITLE
Remove Chakra UI

### ISSUE THREAD

**Issue by KingLyrics** [InternPulse/team-tesla-frontend#42]
@AgonoDavid there was no need to implement chakra ui, all we needed was just formik. Why did you install it? Cause you changed the styling on the certain pages and functionalities have changed. All we needed was formik, you didn't inform me you were going to use Chakra UI and we really didn't need it. The styling were fine as they were before.

**Comment by KingLyrics** [comment]
You'll need to clean up the code, cause really i see no need for chakra ui at all. We already had the design ready, just to implement formik. You'll need to clear up the chakra ui and take it back to the initial styling but keep the formik.

**Comment by AgonoDavid** [comment]
the entire styling is still tailwind css
i just used chakra for the Formik

**Comment by KingLyrics** [comment]
Resolved.
