### ISSUE TITLE
Dashboard Structure 

### ISSUE THREAD

**Issue by KingLyrics** [InternPulse/team-tesla-frontend#6]
Dashboard page is yet to be built.

**Comment by AgonoDavid** [comment]
Once we fully implement Formik, we'll get started with the dashboard
To avoid back and forth

**Comment by KingLyrics** [comment]
That better. Alright

**Comment by KingLyrics** [comment]
Wokring on the structure now.

**Comment by KingLyrics** [comment]
Structure has been implemented
